- apt:
    name:
      - nginx-light
      - nginx-common
    state: latest

- copy:
    src: default
    dest: /etc/nginx/sites-available/default
  notify: restart nginx

- file:
    src: /home/pi/.fldigi/images
    dest: /var/www/html/fldigi
    owner: www-data
    group: www-data
    state: link

- file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- template:
    src: index.html
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data

- get_url:
    url: https://github.com/google/material-design-icons/raw/master/font/MaterialIcons-Regular.ttf
    dest: /var/www/html/MaterialIcons-Regular.ttf

- file:
    path: /var/www/html/{{ item }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  loop:
    - WeatherInformation
    - RadioManuals
    - RadioFrequencies

- copy:
    src: '{{ item }}'
    dest: '/var/www/html/{{ item }}'
    owner: www-data
    group: www-data
    mode: 0644
  loop:
    - WeatherInformation/deutch.pdf
    - WeatherInformation/global.pdf
    - RadioManuals/FT-891-Basic.pdf
    - RadioManuals/FT-891-Advanced.pdf
    - RadioManuals/IC-705-Basic.pdf
    - RadioManuals/IC-705-Advanced.pdf
    - RadioFrequencies/rsgb_band_plan_2021.pdf
