- apt:
    name:
      - gpsd
      - libhamlib-utils
    state: latest
    update_cache: true

- get_url:
    url: http://www.cantab.net/users/john.wiseman/Downloads/Beta/piardopc
    dest: /usr/local/bin/ardopc

- file:
    path: /usr/local/bin/ardopc
    mode: 0755
    owner: root
    group: root

- get_url:
    url: https://www.cantab.net/users/john.wiseman/Downloads/Beta/piARDOP_GUI
    dest: /usr/local/bin/ardop_gui

- file:
    path: /usr/local/bin/ardop_gui
    mode: 0755
    owner: root
    group: root

- get_url:
    url: https://github.com/la5nta/pat/releases/download/v0.10.0/pat_0.10.0_linux_armhf.deb
    dest: /home/pi/Downloads/pat.deb

- apt:
    deb: /home/pi/Downloads/pat.deb
    state: present

- file:
    path: /home/pi/.wl2k
    state: directory
    owner: pi
    group: pi
    mode: 0755

- template:
    src: pat_config.json.j2
    dest: /home/pi/.wl2k/config.json
    mode: 0644
    owner: pi
    group: pi

- template:
    src: run_pat.sh.j2
    dest: /usr/local/bin/run_pat.sh
    mode: 0755
    owner: pi
    group: pi

- copy:
    src: runpat.desktop
    dest: /home/pi/Desktop/runpat.desktop

- name: pre/post flight scripts
  template:
    src: '{{ item }}'
    dest: /usr/local/bin/{{ item }}
    mode: 0755
    owner: root
    group: root
  loop:
    - ardopc_preflight.sh
    - ardopc_postflight.sh
    - pat_preflight.sh
    - pat_postflight.sh

- name: ardopc/pat service files
  template:
    src: '{{ item }}.j2'
    dest: /etc/systemd/system/{{ item }}
    mode: 0644
    owner: root
    group: root
  loop:
  - ardopc.service
  - pat-ardopc.service
  - pat-ax25.service
  - patwinlink.target

- name: reload systemd
  systemd:
    daemon_reload: true
