- apt:
    name:
      - python3
      - python3-pip
    state: latest

- pip:
    name: maidenhead
    state: latest
    executable: pip3

- git:
    repo: https://github.com/m0iax/JS8CallUtilities_V2.git
    dest: /opt/JS8CallUtils

- pip:
    requirements: /opt/JS8CallUtils/requirements.txt
    executable: pip3

- file:
    path: /opt/JS8CallUtils/JS8CallUtils_v2.py
    mode: 0755
