- get_url:
    url: https://github.com/Hamlib/Hamlib/releases/download/{{ hamlib_version }}/hamlib-{{ hamlib_version }}.tar.gz
    dest: /home/pi/hamlib.tar.gz

- unarchive:
    remote_src: true
    src: /home/pi/hamlib.tar.gz
    dest: /home/pi/
    creates: /home/pi/hamlib-{{ hamlib_version }}

- shell:
    cmd: ./configure
    chdir: /home/pi/hamlib-{{ hamlib_version }}
    creates: /home/pi/hamlib-{{ hamlib_version }}/Makefile

- shell:
    cmd: make -j4
    chdir: /home/pi/hamlib-{{ hamlib_version }}
    creates: /home/pi/hamlib-{{ hamlib_version }}/src/rigctl

- shell:
    cmd: make install
    chdir: /home/pi/hamlib-{{ hamlib_version }}
    creates: /usr/bin/rigctl

- shell: ldconfig
